name: Build and deploy web application

on:
  push:
    branches: [ githubactions ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file api/pom.xml
  
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3  # Fetch the repository again to ensure the key is present
        with:
          persist-credentials: false  # Avoid prompting for password on subsequent runs

      - name: Set up SSH key (if not already set up)
        uses: actions/checkout@v3  # Fetch the repository again to ensure the key is present
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: false  # Avoid prompting for password on subsequent runs

      - name: Synchronize files to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" $APP "sudo" $SERVEUR:$PATH

env:
  APP: "./api/target/easyportfolio.war"
  SERVEUR: "belen@86.198.204.181"  # Securely store server details using GitHub secrets
  PATH: "/opt/java/tomcat/tomcat10/webapps/"  # Securely store path using GitHub secrets